# fly.toml app configuration file generated for frontline-v2-remix on 2024-02-13T11:21:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frontline-v2-remix'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
